### ISSUE TITLE
Exception during an import

### ISSUE THREAD

**Issue by vulogov** [arun1729/cog#11]
Python 3.7 when tried to import Graph, throws exception

`>>> from cog.core import Table
>>> from cog.torque import Graph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vulogov/Library/Python/3.7/lib/python/site-packages/cog/torque.py", line 1, in <module>
    from cog.database import Cog
  File "/Users/vulogov/Library/Python/3.7/lib/python/site-packages/cog/database.py", line 18, in <module>
    from core import Table
ModuleNotFoundError: No module named 'core'`

**Comment by arun1729** [comment]
hey @vulogov, sorry Cog currently only runs on python2.7. Support for python 3.x is on the road map.
