### ISSUE TITLE
Can't use it...

### ISSUE THREAD

**Issue by everythingability** [arun1729/cog#12]
Toms-MacBook-Pro:graphtest tomsmith$ pip3 install cogdb
Collecting cogdb
  Using cached cogdb-0.1.2.tar.gz (9.0 kB)
Building wheels for collected packages: cogdb
  Building wheel for cogdb (setup.py) ... done
  Created wheel for cogdb: filename=cogdb-0.1.2-py3-none-any.whl size=8679 sha256=4081944f7748d8b81a35d568a923d0ef3b64629ad2182c6f8f545faf7f4d1d04
  Stored in directory: /Users/tomsmith/Library/Caches/pip/wheels/8b/31/32/daa3d657e6c6bf56132ccca6081671b85dd37a302302e3cefc
Successfully built cogdb
Installing collected packages: cogdb
Successfully installed cogdb-0.1.2
WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
You should consider upgrading via the '/usr/local/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.
Toms-MacBook-Pro:graphtest tomsmith$ python 
Python 3.9.1 (default, Dec 17 2020, 03:41:37) 
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from cog.torque import Graph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/cog/torque.py", line 1, in <module>
    from cog.database import Cog
  File "/usr/local/lib/python3.9/site-packages/cog/database.py", line 18, in <module>
    from core import Table
ModuleNotFoundError: No module named 'core'

**Comment by everythingability** [comment]
I tried it on Google Colab and got the same results.

**Comment by arun1729** [comment]
created #13 to port project to py3.
