### ISSUE TITLE
permission error under pydroid3

### ISSUE THREAD

**Issue by gitshub** [arun1729/cog#50]
Hi,  I'm running pydroid3  (Version 7.52_arm64) under Android 14 and with the program fragment shown I get the permission error shown.  Thanks for your help in advance.

from cog.torque import Graph
g = Graph("people")
g.put("alice","follows","bob")

Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 2, in <module>
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/cog/torque.py", line 88, in __init__
    self.cog = Cog(self.cache)
               ^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/cog/database.py", line 83, in __init__
    self.instance_id = self.init_instance(config.COG_DEFAULT_NAMESPACE)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/cog/database.py", line 101, in init_instance
    if not os.path.exists(self.config.cog_instance_sys_dir()): os.makedirs(self.config.cog_instance_sys_dir())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
OSError: [Errno 30] Read-only file system: '/tmp'

[Program finished]

Here is the install information:

Use prebuilt libraries repository Looking in indexes: http://repo.local Requirement already satisfied: cogdb in /data/user/ 0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/ python3.11/site-packages (3.0.7) Requirement already satisfied: xxhash==3.2.0 in /data/user/0/ru.iiec.pydroid3/files/ aarch64-linux-android/lib/python3.11/site-packages (from cogdb) (3.2.0)

**Comment by arun1729** [comment]
hey @gitshub, looks like '/tmp' directory is read-only in your file system. You can use another directory that you have read/write access by setting the config like this:

```python
from cog import config
config.COG_PATH_PREFIX = "/mydir"
cog = Cog(config)
```

**Comment by gitshub** [comment]
Thanks--that really helped.  I guess the problem was  "unless you're working dir is "/", provide proper, ideally absolute path".
If you like, your documentation could suggest that Android users try code similar to this:

from cog.database import Cog
from cog import config
config.COG_PATH_PREFIX = "/storage/emulated/0/tmp"
cog = Cog(config)

from cog.torque import Graph
g = Graph("people")
g.put("alice","follows","bob")...
